<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LicencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenseRepository extends EntityRepository
{
    public function findByContextOrderByPosition($contextId)
    {
        return $this->createQueryBuilder('l')
            ->where('l.contextId = :contextId')
            ->orderBy('l.position')
            ->setParameter('contextId', $contextId)
            ->getQuery()
            ->getResult();
    }

    public function findHighestPosition($contextId)
    {
        return $this->createQueryBuilder('l')
            ->select('l.position')
            ->where('l.contextId = :contextId')
            ->orderBy('l.position', 'DESC')
            ->setParameter('contextId', $contextId)
            ->getQuery()
            ->setMaxResults(1)
            ->getResult();
    }

    public function updatePositions(array $positions, $portalId)
    {
        //[{"itemId":2},{"itemId":3},{"itemId":1}]
        foreach ($positions as $position => $item) {
            $id = $item['itemId'];

            $update = $this->findOneBy([
                'id' => $id,
                'contextId' => $portalId,
            ]);

            $update->setPosition($position);

            $em = $this->getEntityManager();
            $em->persist($update);
        }

        $em->flush();
    }
}
