parameters:
        legacy.site_index: %kernel.root_dir%/../web/commsy_legacy.php

services:
    # Legacy kernel
    commsy_legacy.legacy_kernel:
        class: CommSy\LegacyBundle\Kernel\LegacyKernel
        arguments: [%legacy.site_index%, @service_container]

    # Event listeners
    commsy_legacy.listener.legacy_kernel_listener:
        class: CommSy\LegacyBundle\EventListener\LegacyKernelListener
        arguments: [@commsy_legacy.legacy_kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }