parameters:

services:
    # Filter types
    commsy.filter.rubric:
        class: CommsyBundle\Filter\RubricFilterType
        arguments: ['@commsy_legacy.room_service', '@request_stack']
        tags:
            - { name: form.type }

    commsy.filter.hashtag:
        class: CommsyBundle\Filter\HashTagFilterType
        arguments: ['@request_stack']
        tags:
            - { name: form.type }

    commsy.filter.category:
        class: CommsyBundle\Filter\CategoryFilterType
        arguments: ['@request_stack', '@commsy_legacy.category_service']
        tags:
            - { name: form.type }
            
    commsy.filter.participant:
        class: CommsyBundle\Filter\ParticipantFilterType
        arguments: ['@request_stack', '@commsy_legacy.user_service']
        tags:
            - { name: form.type }

    # Menu
    commsy.menu.builder:
        class: CommsyBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory', '@commsy_legacy.room_service', '@commsy_legacy.environment', '@commsy_legacy.user_service', '@security.authorization_checker']
        # tags:
        #     - { name: knp_menu.menu_builder, method: createProfileMenu, alias: profile }
        #     - { name: knp_menu.menu_builder, method: createSettingsMenu, alias: settings }
        #     - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
        #     - { name: knp_menu.menu_builder, method: createBreadcrumbMenu, alias: breadcrumb }

    commsy.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ['@commsy.menu.builder', createMainMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    commsy.menu.settings:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createSettingsMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: settings }

    commsy.menu.breadcrumb:
          class: Knp\Menu\MenuItem
          factory: ['@commsy.menu.builder', createBreadcrumbMenu]
          arguments: ['@request_stack']
          tags:
              - { name: knp_menu.menu, alias: breadcrumb }

    commsy.menu.account:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createAccountMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: account }

    commsy.menu.profile:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createProfileMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: profile }

    commsy.menu.voter.request:
        class: CommsyBundle\Menu\Voter\CommsyVoter
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.voter }

    # Voter
    commsy.security.category_voter:
        class: CommsyBundle\Security\Authorization\Voter\CategoryVoter
        arguments: ['@commsy_legacy.environment']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.hashtag_voter:
        class: CommsyBundle\Security\Authorization\Voter\HashtagVoter
        arguments: ['@commsy_legacy.environment']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.item_voter:
        class: CommsyBundle\Security\Authorization\Voter\ItemVoter
        arguments: ['@commsy_legacy.environment', '@commsy_legacy.item_service']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.user_voter:
        class: CommsyBundle\Security\Authorization\Voter\UserVoter
        arguments: ['@commsy_legacy.environment']
        public: false
        tags:
            - { name: security.voter }

    # Exporter
    commsy.export.wordpress:
        class: CommsyBundle\Export\WordpressExporter
        arguments: ['@commsy_legacy.environment']

    commsy.export.wiki:
        class: CommsyBundle\Export\WikiExporter
        arguments: ['@commsy_legacy.environment']

    # EventListener
    kernel.listener.comsy_request:
        class: CommsyBundle\EventListener\CommsyRequestListener
        arguments: ['@commsy_legacy.room_service', '@liip_theme.active_theme', '%liip_theme.themes%']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kernel.listener.commsy_breadcrumb:
        class: CommsyBundle\EventListener\CommsyBreadcrumbListener
        arguments: ['@commsy_legacy.environment', '@commsy_legacy.room_service', '@commsy_legacy.item_service', '@translator', '@router', '@white_october_breadcrumbs']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


    kernel.listener.commsy_login:
        class: CommsyBundle\EventListener\CommsyLoginListener
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kernel.listener.commsy_logging:
        class: CommsyBundle\EventListener\CommsyLoggingListener
        arguments: ['@commsy_legacy.room_service', '@liip_theme.active_theme', '%liip_theme.themes%', '@commsy_legacy.environment']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    commsy.listener.get_room_membership_filter:
        class: CommsyBundle\EventListener\RoomMembershipFilterConditionListener
        arguments: ['@commsy_legacy.user_service']
        tags:
            - { name: kernel.event_listener, event: lexik_form_filter.apply.orm.room_filter.membership , method: onGetFilterCondition }

    commsy.listener.command_error:
        class: CommsyBundle\EventListener\ConsoleErrorListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: console.terminate }

    commsy.listener.command_exception:
        class: CommsyBundle\EventListener\ConsoleExceptionListener
        arguments: ['@logger']
        tags:
            - { name: kernel.event_listener, event: console.exception }

    commsy.etherpad_form_listener:
        class: CommsyBundle\Form\Type\Event\AddEtherpadFormListener
        arguments: ["@service_container"]
        tags:
            - { name: form.event_subscriber }

    # Search
    commsy.search.manager:
        class: CommsyBundle\Search\SearchManager
        arguments: ['@fos_elastica.finder.commsy', '@commsy_legacy.user_service', '@commsy_legacy.item_service']

    # Validator
    commsy.validator.unique_label_name:
        class: CommsyBundle\Validator\Constraints\UniqueLabelNameValidator
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: validator.constraint_validator, alias: alias_name }

    # Form types
    commsy.form.type.general_settings:
        class: CommsyBundle\Form\Type\GeneralSettingsType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.settings.moderation:
        class: CommsyBundle\Form\Type\ModerationSettingsType
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.settings.additional:
        class: CommsyBundle\Form\Type\AdditionalSettingsType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.settings.appearance:
        class: CommsyBundle\Form\Type\AppearanceSettingsType
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: form.type }
            
    commsy.form.type.settings.extension:
        class: CommsyBundle\Form\Type\ExtensionSettingsType
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.settings.invitations:
        class: CommsyBundle\Form\Type\InvitationsSettingsType
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.material:
        class: CommsyBundle\Form\Type\MaterialType
        arguments: ['@commsy.etherpad_form_listener']
        tags:
            - { name: form.type }

    commsy.form.type.announcement:
        class: CommsyBundle\Form\Type\AnnouncementType
        tags:
            - { name: form.type }

    commsy.form.type.itemDescription:
        class: CommsyBundle\Form\Type\ItemDescriptionType
        tags:
            - { name: form.type }

    commsy.form.type.itemWorkflow:
        class: CommsyBundle\Form\Type\ItemWorkflowType
        tags:
            - { name: form.type }

    commsy.form.type.itemLinks:
        class: CommsyBundle\Form\Type\ItemLinksType
        arguments: ['@commsy_legacy.environment', '@commsy_legacy.room_service', '@commsy_legacy.item_service']
        tags:
            - { name: form.type }

    commsy.form.type.section:
        class: CommsyBundle\Form\Type\SectionType
        tags:
            - { name: form.type }

    commsy.form.type.room_profile:
        class: CommsyBundle\Form\Type\RoomProfileType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.room_profile_address:
        class: CommsyBundle\Form\Type\RoomProfileAddressType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.room_profile_contact:
        class: CommsyBundle\Form\Type\RoomProfileContactType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.profile_account:
        class: CommsyBundle\Form\Type\ProfileAccountType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.profile_notifications:
        class: CommsyBundle\Form\Type\ProfileNotificationsType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.profile_additional:
        class: CommsyBundle\Form\Type\ProfileAdditionalType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.upload:
        class: CommsyBundle\Form\Type\UploadType
        tags:
            - { name: form.type }

    commsy.form.type.treechoice:
        class: CommsyBundle\Form\Type\TreeChoiceType
        tags:
            - { name: form.type }

    commsy.form.type.hashtag:
        class: CommsyBundle\Form\Type\HashtagType
        tags:
            - { name: form.type }

    commsy.form.type.category:
        class: CommsyBundle\Form\Type\CategoryType
        tags:
            - { name: form.type }

    commsy.form.type.annotation:
        class: CommsyBundle\Form\Type\AnnotationType
        tags:
            - { name: form.type }

    commsy.form.type.send:
        class: CommsyBundle\Form\Type\SendType
        arguments: ['@commsy.utils.mail_assistant']
        tags:
            - { name: form.type }

    commsy.form.type.user_send:
            class: CommsyBundle\Form\Type\UserSendType
            tags:
                - { name: form.type }
            
    commsy.form.type.sendList:
        class: CommsyBundle\Form\Type\SendListType
        arguments: ['@commsy.utils.mail_assistant']
        tags:
            - { name: form.type }

    commsy.form.type.date:
        class: CommsyBundle\Form\Type\DateType
        tags:
            - { name: form.type }
            
    commsy.form.type.datedetails:
        class: CommsyBundle\Form\Type\DateDetailsType
        tags:
            - { name: form.type }
            
    commsy.form.type.group:
        class: CommsyBundle\Form\Type\GroupType
        tags:
            - { name: form.type }
            
    commsy.form.type.topic:
        class: CommsyBundle\Form\Type\TopicType
        tags:
            - { name: form.type }
            
    commsy.form.type.discussion:
        class: CommsyBundle\Form\Type\DiscussionType
        tags:
            - { name: form.type }
            
    commsy.form.type.discussionarticle:
        class: CommsyBundle\Form\Type\DiscussionArticleType
        tags:
            - { name: form.type }
            
    commsy.form.type.todo:
        class: CommsyBundle\Form\Type\TodoType
        tags:
            - { name: form.type }
            
    commsy.form.type.step:
        class: CommsyBundle\Form\Type\StepType
        tags:
            - { name: form.type }

    commsy.form.type.moderationsupport:
        class: CommsyBundle\Form\Type\ModerationSupportType
        tags:
            - { name: form.type }

    commsy.form.type.participant:
        class: CommsyBundle\Form\Type\ParticipantType
        tags:
            - { name: form.type }

    # Form type extension
    commsy.form.extension.image_type:
        class: CommsyBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

    # Twig
    twig.extension.room:
        class: CommsyBundle\Twig\Extension\RoomExtension
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: twig.extension }

    twig.extension.log:
        class: CommsyBundle\Twig\Extension\LogarithmExtension
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.commsy_markup:
        class: CommsyBundle\Twig\Extension\MarkupExtension
        tags:
            - { name: twig.extension }

    # Controller
    commsy.item_controller:
        class: CommsyBundle\Controller\ItemController

    # Utils
    commsy.utils.mail_assistant:
        class: CommsyBundle\Utils\MailAssistant
        arguments: ['@commsy_legacy.environment', '@translator', '@twig', '%commsy.email.from%']

    commsy.utils.mail_account:
        class: CommsyBundle\Utils\AccountMail
        arguments: ['@commsy_legacy.environment', '@router']

    # Commands
    commsy.command.cron_command:
        class: CommsyBundle\Command\CronCommand
        tags:
            - { name: console.command }

    commsy.command.email_upload:
        class: CommsyBundle\Command\EmailUploadCommand
        tags:
            - { name: console.command }

    commsy.command.db_check:
        class: CommsyBundle\Command\DBCheckCommand
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: console.command }

    commsy.command.setup_dev:
        class: CommsyBundle\Command\SetupDevCommand
        tags:
            - { name: console.command }

    commsy.command.setup_prod:
        class: CommsyBundle\Command\SetupProdCommand
        tags:
            - { name: console.command }

    # API
    commsy.api.soap:
        class: CommsyBundle\Services\SoapService
        arguments: ['@commsy_legacy.environment']

    # Feed
    debril.provider.default:
        class: CommsyBundle\Feed\CommsyFeedContentProvider
        arguments: ['@commsy_legacy.environment', '@request_stack', '@translator', '@commsy.feed.creator_factory']

    commsy.feed.creator_factory:
        class: CommsyBundle\Feed\FeedCreatorFactory
        arguments: ['@commsy_legacy.item_service', '@commsy_legacy.environment', '@translator', '@router']
        calls:
            - [addCreator, ['@commsy.feed.creator.material']]
            - [addCreator, ['@commsy.feed.creator.section']]
            - [addCreator, ['@commsy.feed.creator.annotation']]
            - [addCreator, ['@commsy.feed.creator.group']]
            - [addCreator, ['@commsy.feed.creator.institution']]
            - [addCreator, ['@commsy.feed.creator.topic']]
            - [addCreator, ['@commsy.feed.creator.date']]
            - [addCreator, ['@commsy.feed.creator.user']]
            - [addCreator, ['@commsy.feed.creator.announcement']]
            - [addCreator, ['@commsy.feed.creator.todo']]
            - [addCreator, ['@commsy.feed.creator.step']]
            - [addCreator, ['@commsy.feed.creator.discussion']]
            - [addCreator, ['@commsy.feed.creator.discussion_article']]

    commsy.feed.creator.material:
        class: CommsyBundle\Feed\Creators\MaterialCreator

    commsy.feed.creator.section:
        class: CommsyBundle\Feed\Creators\SectionCreator

    commsy.feed.creator.annotation:
        class: CommsyBundle\Feed\Creators\AnnotationCreator

    commsy.feed.creator.group:
        class: CommsyBundle\Feed\Creators\GroupCreator

    commsy.feed.creator.institution:
        class: CommsyBundle\Feed\Creators\InstitutionCreator

    commsy.feed.creator.topic:
        class: CommsyBundle\Feed\Creators\TopicCreator

    commsy.feed.creator.date:
        class: CommsyBundle\Feed\Creators\DateCreator

    commsy.feed.creator.user:
        class: CommsyBundle\Feed\Creators\UserCreator

    commsy.feed.creator.announcement:
        class: CommsyBundle\Feed\Creators\AnnouncementCreator

    commsy.feed.creator.todo:
        class: CommsyBundle\Feed\Creators\TodoCreator

    commsy.feed.creator.step:
        class: CommsyBundle\Feed\Creators\StepCreator

    commsy.feed.creator.discussion:
        class: CommsyBundle\Feed\Creators\DiscussionCreator

    commsy.feed.creator.discussion_article:
        class: CommsyBundle\Feed\Creators\DiscussionArticleCreator

    # Monolog
    commsy.monolog.handler.doctrine_orm:
        class: CommsyBundle\Monolog\Handler\DoctrineORMHandler
        arguments: ['@doctrine.orm.entity_manager']

    # Services
    commsy.avatar_service:
        class: CommsyBundle\Services\AvatarService
        arguments: ['@commsy_legacy.user_service', '%kernel.root_dir%']
        
    commsy.print_service:
        class: CommsyBundle\Services\PrintService
        arguments: ['@commsy_legacy.environment', '@service_container', '@request_stack']
        
    commsy.copy_service:
        class: CommsyBundle\Services\CopyService
        arguments: ['@commsy_legacy.environment', '@commsy_legacy.room_service', '@commsy_legacy.item_service']