parameters:

services:
    # Filter types
    commsy.filter.rubric:
        class: CommsyBundle\Filter\RubricFilterType
        arguments: ['@commsy_legacy.room_service', '@request_stack']
        tags:
            - { name: form.type }

    commsy.filter.hashtag:
        class: CommsyBundle\Filter\HashTagFilterType
        arguments: ['@request_stack']
        tags:
            - { name: form.type }

    commsy.filter.category:
        class: CommsyBundle\Filter\CategoryFilterType
        arguments: ['@request_stack', '@commsy_legacy.category_service']
        tags:
            - { name: form.type }

    # Converter
    commsy.converter.room:
        class: CommsyBundle\Converter\RoomConverter
        arguments: ['@doctrine.orm.entity_manager']

    commsy.converter.materials:
        class: CommsyBundle\Converter\MaterialsConverter
        arguments: ['@doctrine.orm.entity_manager']

    # Menu
    commsy.menu.builder:
        class: CommsyBundle\Menu\MenuBuilder
        arguments: ['@knp_menu.factory', '@commsy_legacy.room_service', '@commsy_legacy.environment', '@commsy_legacy.user_service', '@security.authorization_checker']
        # tags:
        #     - { name: knp_menu.menu_builder, method: createProfileMenu, alias: profile }
        #     - { name: knp_menu.menu_builder, method: createRoomlistMenu, alias: roomlist }
        #     - { name: knp_menu.menu_builder, method: createSettingsMenu, alias: settings }
        #     - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
        #     - { name: knp_menu.menu_builder, method: createBreadcrumbMenu, alias: breadcrumb }

    commsy.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ['@commsy.menu.builder', createMainMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    commsy.menu.settings:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createSettingsMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: settings }

    commsy.menu.breadcrumb:
          class: Knp\Menu\MenuItem
          factory: ['@commsy.menu.builder', createBreadcrumbMenu]
          arguments: ['@request_stack']
          tags:
              - { name: knp_menu.menu, alias: breadcrumb }

    commsy.menu.profile:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createProfileMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: profile }

    commsy.menu.roomlist:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createRoomlistMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: roomlist }

    # Voter
    commsy.security.category_voter:
        class: CommsyBundle\Security\Authorization\Voter\CategoryVoter
        arguments: ['@commsy_legacy.environment']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.item_voter:
        class: CommsyBundle\Security\Authorization\Voter\ItemVoter
        arguments: ['@commsy_legacy.environment', '@commsy_legacy.item_service']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.user_voter:
        class: CommsyBundle\Security\Authorization\Voter\UserVoter
        arguments: ['@commsy_legacy.environment']
        public: false
        tags:
            - { name: security.voter }

    # Exporter
    commsy.export.wordpress:
        class: CommsyBundle\Export\WordpressExporter
        arguments: ['@commsy_legacy.environment']

    commsy.export.wiki:
        class: CommsyBundle\Export\WikiExporter
        arguments: ['@commsy_legacy.environment']

    # EventListener
    kernel.listener.comsy_request:
        class: CommsyBundle\EventListener\CommsyRequestListener
        arguments: ['@commsy_legacy.room_service', '@liip_theme.active_theme', '%liip_theme.themes%']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kernel.listener.commsy_login:
        class: CommsyBundle\EventListener\CommsyLoginListener
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kernel.listener.commsy_logging:
        class: CommsyBundle\EventListener\CommsyLoggingListener
        arguments: ['@commsy_legacy.room_service', '@liip_theme.active_theme', '%liip_theme.themes%', '@commsy_legacy.environment']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Search
    commsy.search_builder:
        class: CommsyBundle\Search\SearchBuilder
        arguments: ['@fos_elastica.finder.commsy.material']

    # Form types
    commsy.form.type.general_settings:
        class: CommsyBundle\Form\Type\GeneralSettingsType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.settings.appearance:
        class: CommsyBundle\Form\Type\AppearanceSettingsType
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: form.type }
            
    commsy.form.type.settings.extension:
        class: CommsyBundle\Form\Type\ExtensionSettingsType
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.material:
        class: CommsyBundle\Form\Type\MaterialType
        tags:
            - { name: form.type }

    commsy.form.type.announcement:
        class: CommsyBundle\Form\Type\AnnouncementType
        tags:
            - { name: form.type }

    commsy.form.type.itemDescription:
        class: CommsyBundle\Form\Type\ItemDescriptionType
        tags:
            - { name: form.type }

    commsy.form.type.itemWorkflow:
        class: CommsyBundle\Form\Type\ItemWorkflowType
        tags:
            - { name: form.type }

    commsy.form.type.itemLinks:
        class: CommsyBundle\Form\Type\ItemLinksType
        arguments: ['@commsy_legacy.environment', '@commsy_legacy.room_service', '@commsy_legacy.item_service']
        tags:
            - { name: form.type }

    commsy.form.type.section:
        class: CommsyBundle\Form\Type\SectionType
        tags:
            - { name: form.type }

    commsy.form.type.room_profile:
        class: CommsyBundle\Form\Type\RoomProfileType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.combine_profile:
        class: CommsyBundle\Form\Type\CombineProfileType
        arguments: ['@doctrine.orm.entity_manager', '@commsy_legacy.environment']
        tags:
            - { name: form.type }

    commsy.form.type.upload:
        class: CommsyBundle\Form\Type\UploadType
        tags:
            - { name: form.type }

    commsy.form.type.treechoice:
        class: CommsyBundle\Form\Type\TreeChoiceType
        tags:
            - { name: form.type }

    commsy.form.type.hashtag:
        class: CommsyBundle\Form\Type\HashtagType
        tags:
            - { name: form.type }

    commsy.form.type.category:
        class: CommsyBundle\Form\Type\CategoryType
        tags:
            - { name: form.type }

    commsy.form.type.annotation:
        class: CommsyBundle\Form\Type\AnnotationType
        tags:
            - { name: form.type }

    commsy.form.type.send:
        class: CommsyBundle\Form\Type\SendType
        arguments: ['@commsy.utils.mail_assistant']
        tags:
            - { name: form.type }
            
    commsy.form.type.sendList:
        class: CommsyBundle\Form\Type\SendListType
        arguments: ['@commsy.utils.mail_assistant']
        tags:
            - { name: form.type }

    commsy.form.type.date:
        class: CommsyBundle\Form\Type\DateType
        tags:
            - { name: form.type }
            
    commsy.form.type.datedetail:
        class: CommsyBundle\Form\Type\DateDetailType
        tags:
            - { name: form.type }
            
    commsy.form.type.group:
        class: CommsyBundle\Form\Type\GroupType
        tags:
            - { name: form.type }
            
    commsy.form.type.topic:
        class: CommsyBundle\Form\Type\TopicType
        tags:
            - { name: form.type }
            
    commsy.form.type.discussion:
        class: CommsyBundle\Form\Type\DiscussionType
        tags:
            - { name: form.type }
            
    commsy.form.type.discussionarticle:
        class: CommsyBundle\Form\Type\DiscussionArticleType
        tags:
            - { name: form.type }
            
    commsy.form.type.todo:
        class: CommsyBundle\Form\Type\TodoType
        tags:
            - { name: form.type }
            
    commsy.form.type.step:
        class: CommsyBundle\Form\Type\StepType
        tags:
            - { name: form.type }

    commsy.form.type.moderationsupport:
        class: CommsyBundle\Form\Type\ModerationSupportType
        tags:
            - { name: form.type }

    # Form type extension
    commsy.form.extension.image_type:
        class: CommsyBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

    # Twig
    twig.extension.room:
        class: CommsyBundle\Twig\Extension\RoomExtension
        arguments: ['@commsy_legacy.environment']
        tags:
            - { name: twig.extension }

    # Controller
    commsy.item_controller:
        class: CommsyBundle\Controller\ItemController

    # Utils
    commsy.utils.mail_assistant:
        class: CommsyBundle\Utils\MailAssistant
        arguments: ['@commsy_legacy.environment', '@translator', '@twig']

    # Commands
    commsy.command.cron_command:
        class: CommsyBundle\Command\CronCommand
        arguments: ['%kernel.root_dir%', '@commsy_legacy.environment']
        tags:
            - { name: console.command }

    # API
    commsy.api.soap:
        class: CommsyBundle\Services\SoapService
        arguments: ['@commsy_legacy.environment']
