parameters:

services:
    commsy.room_feed_generator:
        class: Commsy\LegacyBundle\Utils\RoomFeedGenerator
        arguments: ["@commsy_legacy.environment"]

    commsy.tag_manager:
        class: Commsy\LegacyBundle\Utils\TagManager
        arguments: ["@commsy_legacy.environment"]

    commsy.room_manager:
        class: Commsy\LegacyBundle\Utils\RoomManager
        arguments: ["@commsy_legacy.environment"]