parameters:

services:
    commsy.room_feed_generator:
        class: CommsyBundle\Utils\RoomFeedGenerator
        arguments: ["@commsy_legacy.environment"]

    commsy.tag_manager:
        class: CommsyBundle\Utils\TagManager
        arguments: ["@commsy_legacy.environment"]

    commsy.room_manager:
        class: CommsyBundle\Utils\RoomManager
        arguments: ["@commsy_legacy.environment"]