parameters:

services:
    # Filter types
    commsy.filter.rubric:
        class: CommsyBundle\Filter\RubricFilterType
        arguments: [@commsy.room_service, @request_stack]
        tags:
            - { name: form.type, alias: rubric_filter }

    # Converter
    commsy.converter.room:
        class: CommsyBundle\Converter\RoomConverter
        arguments: [@doctrine.orm.entity_manager]

    # Voter
    commsy.security.category_voter:
        class: CommsyBundle\Security\Authorization\Voter\CategoryVoter
        arguments: [@commsy_legacy.environment]
        public: false
        tags:
            - { name: security.voter }

    commsy.security.item_voter:
        class: CommsyBundle\Security\Authorization\Voter\ItemVoter
        arguments: [@commsy_legacy.environment, @commsy.item_service]
        public: false
        tags:
            - { name: security.voter }

    # Search
    commsy.search_builder:
        class: CommsyBundle\Search\SearchBuilder
        arguments: [@fos_elastica.finder.commsy]