parameters:

services:
    # Filter types
    commsy.filter.rubric:
        class: CommsyBundle\Filter\RubricFilterType
        arguments: [@commsy.room_service, @request_stack]
        tags:
            - { name: form.type, alias: rubric_filter }

    commsy.filter.hashtag:
        class: CommsyBundle\Filter\HashTagFilterType
        arguments: [@request_stack]
        tags:
            - { name: form.type, alias: hashtag_filter }

    commsy.filter.category:
        class: CommsyBundle\Filter\CategoryFilterType
        arguments: [@request_stack, @commsy.category_service]
        tags:
            - { name: form.type, alias: category_filter }

    # Converter
    commsy.converter.room:
        class: CommsyBundle\Converter\RoomConverter
        arguments: [@doctrine.orm.entity_manager]

    # Menu
    commsy.menu.builder:
        class: CommsyBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@commsy.room_service", "@commsy_legacy.environment", "@commsy.user_service", "@security.authorization_checker"]

    commsy.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: commsy.menu.builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    commsy.menu.settings:
        class: Knp\Menu\MenuItem
        factory_service: commsy.menu.builder
        factory_method: createSettingsMenu
        arguments: [@request_stack]
        tags:
            - { name: knp_menu.menu, alias: settings }

    commsy.menu.breadcrumb:
          class: Knp\Menu\MenuItem
          factory_service: commsy.menu.builder
          factory_method: createBreadcrumbMenu
          arguments: ["@request_stack"]
          tags:
              - { name: knp_menu.menu, alias: breadcrumb }

    commsy.menu.profile:
        class: Knp\Menu\MenuItem
        factory_service: commsy.menu.builder
        factory_method: createProfileMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: profile }

    commsy.menu.roomlist:
        class: Knp\Menu\MenuItem
        factory_service: commsy.menu.builder
        factory_method: createRoomlistMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: roomlist }

    # Voter
    commsy.security.category_voter:
        class: CommsyBundle\Security\Authorization\Voter\CategoryVoter
        arguments: [@commsy_legacy.environment]
        public: false
        tags:
            - { name: security.voter }

    commsy.security.item_voter:
        class: CommsyBundle\Security\Authorization\Voter\ItemVoter
        arguments: [@commsy_legacy.environment, @commsy.item_service]
        public: false
        tags:
            - { name: security.voter }

    commsy.security.user_voter:
        class: CommsyBundle\Security\Authorization\Voter\UserVoter
        arguments: [@commsy_legacy.environment]
        public: false
        tags:
            - { name: security.voter }

    # EventListener
    kernel.listener.comsy_request:
        class: CommsyBundle\EventListener\CommsyRequestListener
        arguments: [@commsy.room_service, @liip_theme.active_theme, %liip_theme.themes%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Search
    commsy.search_builder:
        class: CommsyBundle\Search\SearchBuilder
        arguments: [@fos_elastica.finder.commsy.material]

    # Form
    commsy.form.type.general_settings:
        class: CommsyBundle\Form\Type\GeneralSettingsType
        arguments: [@doctrine.orm.entity_manager, @commsy_legacy.environment]
        tags:
            - { name: form.type, alias: general_settings }

    commsy.form.type.settings.appearance:
        class: CommsyBundle\Form\Type\AppearanceSettingsType
        arguments: [@commsy_legacy.environment]
        tags:
            - { name: form.type, alias: appearance_settings }

    commsy.form.type.material:
        class: CommsyBundle\Form\Type\MaterialType
        tags:
            - { name: form.type, alias: material }

    commsy.form.type.itemDescription:
        class: CommsyBundle\Form\Type\ItemDescriptionType
        tags:
            - { name: form.type, alias: itemDescription }

    commsy.form.type.itemWorkflow:
        class: CommsyBundle\Form\Type\ItemWorkflowType
        tags:
            - { name: form.type, alias: itemWorkflow }

    commsy.form.type.itemLinks:
        class: CommsyBundle\Form\Type\ItemLinksType
        arguments: ["@commsy_legacy.environment", @commsy.room_service, @commsy.item_service]
        tags:
            - { name: form.type, alias: itemLinks }

    commsy.form.type.section:
        class: CommsyBundle\Form\Type\SectionType
        tags:
            - { name: form.type, alias: section }

    commsy.form.extension.image_type:
        class: CommsyBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file }

    commsy.form.type.room_profile:
        class: CommsyBundle\Form\Type\RoomProfileType
        arguments: [@doctrine.orm.entity_manager, @commsy_legacy.environment]
        tags:
            - { name: form.type, alias: room_profile }

    commsy.form.type.combine_profile:
        class: CommsyBundle\Form\Type\CombineProfileType
        arguments: [@doctrine.orm.entity_manager, @commsy_legacy.environment]
        tags:
            - { name: form.type, alias: combine_profile }

    commsy.form.type.upload:
        class: CommsyBundle\Form\Type\UploadType
        tags:
            - { name: form.type, alias: upload }

    commsy.form.type.treechoice:
        class: CommsyBundle\Form\Type\TreeChoiceType
        tags:
            - { name: form.type, alias: treechoice }

    commsy.form.type.hashtag:
        class: CommsyBundle\Form\Type\HashtagType
        tags:
            - { name: form.type, alias: hashtag }

    commsy.form.type.category:
        class: CommsyBundle\Form\Type\CategoryType
        tags:
            - { name: form.type, alias: category }

    commsy.form.type.annotation:
        class: CommsyBundle\Form\Type\AnnotationType
        tags:
            - { name: form.type, alias: annotation }

    # Twig
    twig.extension.room:
        class: CommsyBundle\Twig\Extension\RoomExtension
        arguments: ["@commsy_legacy.environment"]
        tags:
            - { name: twig.extension }

    # Controller
    commsy.item_controller:
        class: CommsyBundle\Controller\ItemController