api_platform:
    title: CommSy
    description: A web-based community system.
    version: 2.1.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        json:
            mime_types: ['application/json']
    docs_formats:
        json: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/WOPI/REST/Request'
