doctrine_migrations:
    enable_service_migrations: true
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'
    enable_profiler: false

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 255
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'

    # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    organize_migrations: false
