nelmio_api_doc:
    documentation:
        info:
            title: CommSy
            description: A web-based community system.
            version: 0.3.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api/v2(?!/doc$) # Accepts routes under /api/v2 except /api/v2/doc

    models:
        use_jms: false
