twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/uikit_layout.html.twig'
        - '@SpiriitFormFilter/Form/form_div_layout.html.twig'
    globals:
        commsy: '@App\Twig\CommsyGlobals'


when@test:
    twig:
        strict_variables: true
