vich_uploader:
    db_driver: orm

    mappings:
        portal_logo:
            uri_prefix: /files/portal/logos
            upload_destination: '%kernel.project_dir%/files/portal/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true

        server_logo:
            uri_prefix: /files/server
            upload_destination: '%kernel.project_dir%/files/server'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
