services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql:rw
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=!ChangeMe!

  elastic:
    build: ./docker/elasticsearch
    restart: unless-stopped
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1

  php:
    image: ${IMAGES_PREFIX:-}app-php
    depends_on:
      - db
      - elastic
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@db:3306/${MYSQL_DB:-app}?serverVersion=${MYSQL_VERSION:-10.11.2-MariaDB}&charset=${MYSQL_CHARSET:-utf8mb4}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - commsy_data:/app/files
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

volumes:
  caddy_data:
  caddy_config:
  db_data:
  elastic_data:
  commsy_data:
