version: "3.4"

services:

  db:
    image: mariadb:10.6
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=commsy
      - MYSQL_USER=commsy
      - MYSQL_PASSWORD=commsy

  elastic:
    build: ./docker/elasticsearch
    restart: unless-stopped
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  caddy:
    image: commsy/caddy
    build:
      context: ./
      target: commsy_caddy
    depends_on:
      - php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp

  php:
    image: commsy/php
    build:
      context: .
      target: commsy_php
    depends_on:
      - db
      - elastic
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - php_socket:/var/run/php
      - commsy_data:/var/www/html/files
#    environment:
#      DATABASE_URL: mysql://${MYSQL_USER:-commsy}:${MYSQL_PASSWORD:-commsy}@db:3306/${MYSQL_DB:-commsy}?serverVersion=${MYSQL_VERSION:-5.6}

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  db_data:
  elastic_data:
  commsy_data:
