# Development environment override
services:
  
  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###
  
  db:
    ports:
      - "3106:3306"

  elastic:
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"

  php:
    build:
      target: commsy_php_dev
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/var/www/html:rw,cached
      - ./docker/php/conf.d/commsy.dev.ini:/usr/local/etc/php/conf.d/commsy.dev.ini:ro
      # If you develop on Mac you can remove the var/ directory from the bind-mount
      # for better performance by enabling the next line
      # - /srv/app/var
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./public:/var/www/html/public:ro,cached
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
