define({
	additionalAdd:				"Weiteren Empfänger hinzufügen",
	additionalDescription:		"Zusätzlich zur Auswahl können Sie hier weitere Empfänger ergänzen.",
	additionalFirstName:		"Vorname",
	additionalLabel:			"Zusätzlicher Empfänger",
	additionalLastName:			"Nachname",
	additionalMail:				"Mailadresse",
	all:						"Alle Mitglieder im Raum",
	buttonClose:				"Schließen",
	buttonSend:					"Versenden",
	close:						"schließen",
	copyToSender:				"Kopie an Absender",
	errorMail:					"Falsches Mail-Format",
	errorMissing:				"Bitte geben Sie einen Wert an",
	no:							"Nein",
	recipient:					"EmpfängerIn:",
	sendTo:						"Senden an:",
	sendToAttendees:			"An die Teilnehmenden senden",
	sendToInstitution:			"An Institution senden:",
	sendToGroups:				"An folgende Gruppen senden:",
	sendToProcessors:			"An die Zuständigen senden",
	subject:					"Betreff",
	title:						"Versenden",
	yes:						"Ja"
});