<?php

namespace CommsyBundle\Repository;

/**
 * LicencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicencesRepository extends \Doctrine\ORM\EntityRepository
{
}
