imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "commsy_test_db"
        port:     "3306"
        dbname:   "test"
        user:     "test"
        password: "test"