imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "commsy_test_db"
        port:     "3306"
        dbname:   "commsy"
        user:     "root"
        password: "root"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true