# Note on how hashtags and tags properties are generated:
# Setting the property path to false will disable transformation of that value.
# In this case the mapping will be created but no value will be populated while indexing.
# The value is populated by listening to the POST_TRANSFORM event.
#
# This is done in @see CommsyBundle\EventListener\ElasticCustomPropertyListener
#
#

fos_elastica:
    clients:
        default:
            host: %elastic_host%
            port: %elastic_port%
            #username: %elastic_user%
            #password: %elastic_password%

    indexes:
        commsy:
            client: default

            finder: ~

            settings:
                analysis:
                    filter:
                        autocomplete_filter:
                            type: edge_ngram
                            min_gram: 1
                            max_gram: 20

                    analyzer:
                        autocomplete:
                            type: custom
                            tokenizer: standard
                            filter:
                                - lowercase
                                - autocomplete_filter

            types:
                # Announcements
                announcement:
                    indexable_callback: isIndexable
                    properties:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        creationDate:
                            type: date
                            format: date_optional_time
                        title:
                            type: text
                            analyzer: autocomplete
                            search_analyzer: standard
                        description: ~
                        hashtags:
                            property_path: false
                        tags:
                            property_path: false
                        endDate:
                            type: date
                            format: date_optional_time
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Announcement
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                # dates
                date:
                    indexable_callback: isIndexable
                    properties:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        creationDate:
                            type: date
                            format: date_optional_time
                        title:
                            type: text
                            analyzer: autocomplete
                            search_analyzer: standard
                        description: ~
                        hashtags:
                            property_path: false
                        tags:
                            property_path: false
                        datetimeStart:
                            type: date
                            format: date_optional_time
                        datetimeEnd:
                            type: date
                            format: date_optional_time
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Dates
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                # discussions:
                discussion:
                    indexable_callback: isIndexable
                    properties:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        creationDate:
                            type: date
                            format: date_optional_time
                        title:
                            type: text
                            analyzer: autocomplete
                            search_analyzer: standard
                        hashtags:
                            property_path: false
                        tags:
                            property_path: false
                        discussionarticles:
                            type: 'nested'
                            properties:
                                subject: ~
                                description: ~
                                files:
                                    type: 'nested'
                                    properties:
                                        filename: ~
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Discussions
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~


                # labels: (groups, topics, institutions)
                label:
                    indexable_callback: isIndexable
                    properties:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        creationDate:
                            type: date
                            format: date_optional_time
                        name: ~
                        type: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Labels
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                # room:
                room:
                    indexable_callback: isIndexable
                    properties:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        title:
                            type: text
                            analyzer: autocomplete
                            search_analyzer: standard
                        contactPersons: ~
                        roomDescription: ~
                        type: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Room
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~


                # todos:
                todo:
                    indexable_callback: isIndexable
                    properties:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        title:
                            type: text
                            analyzer: autocomplete
                            search_analyzer: standard
                        date:
                            type: date
                            format: date_optional_time
                        description: ~
                        hashtags:
                            property_path: false
                        tags:
                            property_path: false
                        steps:
                            type: 'nested'
                            properties:
                                title: ~
                                description: ~
                                files:
                                    type: 'nested'
                                    properties:
                                        filename: ~
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Todos
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~


                
                # User
                user:
                    indexable_callback: isIndexable
                    properties:
                        userId: ~
                        contextId:
                            type: integer
                        firstName: ~
                        lastName: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\User
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                # materials:
                material:
                    indexable_callback: 'isIndexable'
                    properties:
                        versionId:
                            type: integer
                        contextId:
                            type: integer
                        title:
                            type: text
                            analyzer: autocomplete
                            search_analyzer: standard
                        description: ~
                        hashtags:
                            property_path: false
                        tags:
                            property_path: false
                        sections:
                            type: 'nested'
                            properties:
                                title: ~
                                description: ~
                                files:
                                    type: 'nested'
                                    properties:
                                        filename: ~
                        creator:
                            type: 'object'
                            properties:
                                userId: ~
                                status: ~
                                firstname: ~
                                lastname: ~
                                city: ~
                        modifier:
                            type: 'object'
                            properties:
                                userId: ~
                                status: ~
                                firstname: ~
                                lastname: ~
                                city: ~
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                                content:
                                    type: attachment

                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Materials
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~