fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }

    indexes:
        commsy:
            client: default

            finder: ~

            settings:
                analysis:
                    filter:
                        autocomplete_filter:
                            type: edge_ngram
                            min_gram: 1
                            max_gram: 20

                    analyzer:
                        autocomplete:
                            type: custom
                            tokenizer: standard
                            filter:
                                - lowercase
                                - autocomplete_filter

            types:
                # Announcements
                announcement:
                    indexable_callback: isIndexable
                    mappings:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~

                        creationDate:
                            type: date
                            format: date_optional_time
                        title:
                            type: string
                            analyzer: autocomplete
                            search_analyzer: standard
                        description: ~
                        endDate:
                            type: date
                            format: date_optional_time
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Announcement
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                # dates
                dates:
                    indexable_callback: isIndexable
                    mappings:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        creationDate:
                            type: date
                            format: date_optional_time
                        title:
                            type: string
                            analyzer: autocomplete
                            search_analyzer: standard
                        description: ~
                        datetimeStart:
                            type: date
                            format: date_optional_time
                        datetimeEnd:
                            type: date
                            format: date_optional_time
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Dates
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                # discussions:
                discussions:
                    indexable_callback: isIndexable
                    mappings:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        creationDate:
                            type: date
                            format: date_optional_time
                        title:
                            type: string
                            analyzer: autocomplete
                            search_analyzer: standard
                        discussionarticles:
                            type: 'nested'
                            properties:
                                subject: ~
                                description: ~
                                files:
                                    type: 'nested'
                                    properties:
                                        filename: ~
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Discussions
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~


                # labels: (groups, topics, institutions)
                labels:
                    indexable_callback: isIndexable
                    mappings:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        creationDate:
                            type: date
                            format: date_optional_time
                        name: ~
                        type: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Labels
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                # room:
                room:
                    indexable_callback: isIndexable
                    mappings:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        title:
                            type: string
                            analyzer: autocomplete
                            search_analyzer: standard
                        contactPersons: ~
                        roomDescription: ~
                        type: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Room
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~


                # todos:
                todos:
                    indexable_callback: isIndexable
                    mappings:
                        contextId:
                            type: integer
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        title:
                            type: string
                            analyzer: autocomplete
                            search_analyzer: standard
                        date:
                            type: date
                            format: date_optional_time
                        description: ~
                        steps:
                            type: 'nested'
                            properties:
                                title: ~
                                description: ~
                                files:
                                    type: 'nested'
                                    properties:
                                        filename: ~
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Todos
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~


                
                # User
                user:
                    indexable_callback: isIndexable
                    mappings:
                        userId: ~
                        contextId:
                            type: integer
                        firstName: ~
                        lastName: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\User
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                # materials:
                materials:
                    indexable_callback: 'isIndexable'
                    mappings:
                        versionId:
                            type: integer
                        contextId:
                            type: integer
                        title:
                            type: string
                            analyzer: autocomplete
                            search_analyzer: standard
                        description: ~
                        sections:
                            type: 'nested'
                            properties:
                                title: ~
                                description: ~
                                files:
                                    type: 'nested'
                                    properties:
                                        filename: ~
                        creator:
                            type: 'object'
                            properties:
                                userId: ~
                                status: ~
                                firstname: ~
                                lastname: ~
                                city: ~
                        modifier:
                            type: 'object'
                            properties:
                                userId: ~
                                status: ~
                                firstname: ~
                                lastname: ~
                                city: ~
                        files:
                            type: 'nested'
                            properties:
                                filename: ~
                                content:
                                    type: attachment

                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Materials
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~
                announcement:
                    indexable_callback: 'isIndexable'
                    mappings:
                        contextId:
                            type: integer
                        title:
                            type: string
                            analyzer: autocomplete
                            search_analyzer: standard
                        description: ~
                        creator:
                            type: 'object'
                            properties:
                                userId: ~
                                status: ~
                                firstname: ~
                                lastname: ~
                                city: ~
                        modifier:
                            type: 'object'
                            properties:
                                userId: ~
                                status: ~
                                firstname: ~
                                lastname: ~
                                city: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Announcement
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~
