fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        commsy:
            client: default

            finder: ~

            settings:
                analysis:
                    filter:
                        autocomplete_filter:
                            type: edge_ngram
                            min_gram: 1
                            max_gram: 20

                    analyzer:
                        autocomplete:
                            type: custom
                            tokenizer: standard
                            filter:
                                - lowercase
                                - autocomplete_filter

            types:
                user:
                    indexable_callback: 'isIndexable'
                    mappings:
                        userId: ~
                        contextId: ~
                        status: ~
                        firstname: ~
                        lastname: ~
                        city: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\User
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                material:
                    indexable_callback: 'isIndexable'
                    mappings:
                        versionId: ~
                        contextId: ~
                        title:
                            type: string
                            analyzer: autocomplete
                            search_analyzer: standard
                        description: ~
                        sections:
                            type: 'nested'
                            properties:
                                title: ~
                                description: ~
                        creator:
                            type: 'object'
                            properties:
                                userId: ~
                                status: ~
                                firstname: ~
                                lastname: ~
                                city: ~
                        modifier:
                            type: 'object'
                            properties:
                                userId: ~
                                status: ~
                                firstname: ~
                                lastname: ~
                                city: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Materials
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~