fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }

    indexes:
        commsy:
            client: default

            finder: ~

            settings:
                analysis:
                    filter:
                        autocomplete_filter:
                            type: edge_ngram
                            min_gram: 1
                            max_gram: 20

                    analyzer:
                        autocomplete:
                            type: custom
                            tokenizer: standard
                            filter:
                                - lowercase
                                - autocomplete_filter

            types:
                # Announcements
                announcement:
                    indexable_callback: isIndexable
                    mappings:
                        contextId: ~
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~

                        creationDate:
                            type: date
                            format: date_optional_time
                        title: ~
                        description: ~
                        endDate:
                            type: date
                            format: date_optional_time

                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Announcement
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~

                # dates
                dates:
                    indexable_callback: isIndexable
                    mappings:
                        contextId: ~
                        creator:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        modifier:
                            type: object
                            properties:
                                userId: ~
                                firstName: ~
                                lastName: ~
                        creationDate:
                            type: date
                            format: date_optional_time
                        title: ~
                        description: ~
                        datetimeStart:
                            type: date
                            format: date_optional_time
                        datetimeEnd:
                            type: date
                            format: date_optional_time
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\Dates
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~


                # discussions:
                # labels:
                # materials:
                # room:
                # todos:
                
                # User
                user:
                    indexable_callback: isIndexable
                    mappings:
                        userId: ~
                        contextId: ~
                        firstName: ~
                        lastName: ~
                    persistence:
                        driver: orm
                        model: CommsyBundle\Entity\User
                        identifier: itemId
                        finder: ~
                        provider: ~
                        listener: ~


                # material:
                #     indexable_callback: 'isIndexable'
                #     mappings:
                #         versionId: ~
                #         contextId: ~
                #         title:
                #             type: string
                #             analyzer: autocomplete
                #             search_analyzer: standard
                #         description: ~
                #         sections:
                #             type: 'nested'
                #             properties:
                #                 title: ~
                #                 description: ~
                #         creator:
                #             type: 'object'
                #             properties:
                #                 userId: ~
                #                 status: ~
                #                 firstname: ~
                #                 lastname: ~
                #                 city: ~
                #         modifier:
                #             type: 'object'
                #             properties:
                #                 userId: ~
                #                 status: ~
                #                 firstname: ~
                #                 lastname: ~
                #                 city: ~
                    # persistence:
                    #     driver: orm
                    #     model: CommsyBundle\Entity\Materials
                    #     identifier: itemId
                    #     finder: ~
                    #     provider: ~
                    #     listener: ~