services:
  onlyoffice:
    build: ./docker/office
    restart: unless-stopped
    environment:
      WOPI_ENABLED: true
      SSL_CERTIFICATE_PATH: /app/onlyoffice/DocumentServer/data/certs/onlyoffice.crt
      SSL_KEY_PATH: /app/onlyoffice/DocumentServer/data/certs/onlyoffice.key
    ports:
      - '8443:443'
