version: "3.4"

services:
  elastic:
    build: ./docker/elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - "xpack.security.enabled=false"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-headers=Authorization"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  php:
    depends_on:
      - elastic

volumes:
  elastic-data: