#  commsy_kibana:
#    image: docker.elastic.co/kibana/kibana:5.4.0
#    container_name: commsy_kibana
#    ports:
#      - "5601:5601"
#    links:
#      - commsy_elastic:elasticsearch
#    environment:
#      XPACK_SECURITY_ENABLED: "false"

#  commsy_head:
#    image: mobz/elasticsearch-head:5
#    container_name: commsy_head
#    ports:
#      - "5601:9100"
#    links:
#      - commsy_elastic