version: '2'

services:
  commsy_db:
    image: mariadb:10.1
    container_name: commsy_db
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commsy
      MYSQL_USER: commsy
      MYSQL_PASSWORD: commsy

  commsy_nginx:
    build: ./nginx
    container_name: commsy_nginx
    ports:
      - "8080:80"
    links:
      - commsy_php
    volumes_from:
      - commsy_php
    volumes:
      - "./.data/logs/nginx:/var/log/nginx"

  commsy_elastic:
    build: ./elasticsearch
    container_name: commsy_elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./.data/elastic:/usr/share/elasticsearch/data"

  commsy_php:
    build: ./commsy
    container_name: commsy_php
    expose:
      - "9001"
    volumes:
      - "./.data/logs/commsy:/var/www/commsy/var/logs"
    links:
      - commsy_db
      - commsy_elastic