version: '2'

services:
  commsy_php:
    build: ./commsy_dev
    volumes:
      - commsy-unison-sync:/var/www/commsy:nocopy
      - "./.data/debug:/tmp"
    links:
      - commsy_mailhog

  commsy_mailhog:
    image: mailhog/mailhog:latest
    container_name: commsy_mailhog
    ports:
      - "8025:8025"

  commsy_kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: commsy_kibana
    ports:
      - "5601:5601"
    links:
      - commsy_elastic:elasticsearch
    environment:
      XPACK_SECURITY_ENABLED: "false"

  commsy_elastic:
    environment:
      cluster.routing.allocation.disk.threshold_enabled: "false"

  commsy_mediawiki:
    image: wikimedia/mediawiki:1.30.0-wmf4
    #build: ./commsy_wordpress
    container_name: commsy_mediawiki
    volumes:
     - "./.data/mediawiki:/var/www/html"
    links:
     - commsy_mediawiki_mysql
    environment:
     - MEDIAWIKI_SITE_SERVER=http://localhost:8082
     - MEDIAWIKI_SITE_NAME=CommSy 9
     - MEDIAWIKI_ADMIN_PASS=admin
     - MEDIAWIKI_DB_HOST=commsy_mediawiki_mysql
     - MEDIAWIKI_DB_USER=root
     - MEDIAWIKI_DB_PASSWORD=password
     - MEDIAWIKI_DB_TYPE=mysql
     - MEDIAWIKI_DB_PORT=3306
     - MEDIAWIKI_DB_NAME=mediawiki
    ports:
     - "8082:80"

  commsy_mediawiki_mysql:
    image: mysql:5.7.4
    container_name: commsy_mediawiki_mysql
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=mediawiki
    volumes:
     - "./.data/db_mediawiki:/var/lib/mysql"
    ports:
     - "3307:3306"

volumes:
  commsy-unison-sync:
    external: true