version: '2'

services:
  commsy_php:
    build: ./commsy_dev
    volumes:
      - commsy-unison-sync:/var/www/commsy:nocopy
      - "./.data/debug:/tmp"
    links:
      - commsy_mailhog
      - commsy_wordpress

  commsy_mailhog:
    image: mailhog/mailhog:latest
    container_name: commsy_mailhog
    ports:
      - "8025:8025"

  commsy_kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    container_name: commsy_kibana
    ports:
      - "5601:5601"
    links:
      - commsy_elastic:elasticsearch
    environment:
      XPACK_SECURITY_ENABLED: "false"

  commsy_elastic:
    environment:
      cluster.routing.allocation.disk.threshold_enabled: "false"

  commsy_wordpress:
    image: wordpress
    container_name: commsy_wordpress
    links:
     - commsy_wordpress_mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_HOST=commsy_wordpress_mysql
    ports:
     - "8081:80"

  commsy_wordpress_mysql:
    image: mysql:5.7
    container_name: commsy_wordpress_mysql
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress

volumes:
  commsy-unison-sync:
    external: true