version: '2'

services:
  commsy_php:
    build: ./commsy_dev
    volumes:
      - commsy-unison-sync:/var/www/commsy:rw
    links:
      - commsy_mailhog

  commsy_mailhog:
    image: mailhog/mailhog:latest
    container_name: commsy_mailhog
    ports:
      - "8025:8025"

  commsy_kibana:
    image: kibana:latest
    container_name: commsy_kibana
    ports:
      - "5601:5601"
    links:
      - commsy_elastic:elasticsearch

volumes:
  commsy-unison-sync:
    external: true