version: "2"

services:
  commsy_db:
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=commsy"
      - "MYSQL_USER=commsy"
      - "MYSQL_PASSWORD=commsy"

  commsy_nginx:
    ports:
      - "8080:80"
    volumes:
      - "./../:/var/www/commsy:cached"

  commsy_elastic:
    ports:
      - "9200:9200"
    environment:
      - "xpack.security.enabled=false"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-headers=Authorization"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  commsy_php:
    volumes:
      - "./../:/var/www/commsy:cached"
      - "./.data/debug:/tmp"
    environment:
      COMMSY_DB_USER: commsy
      COMMSY_DB_PASSWORD: commsy
      COMMSY_DB_NAME: commsy