version: "3.4"

services:
  mediawiki:
    build: ./docker/wiki
    depends_on:
      - mediawiki_db
    ports:
      - "82:80"

  mediawiki_db:
    image: mariadb:10.1
    ports:
      - "3108:3306"
    volumes:
      - wiki-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=mediawiki

  php:
    depends_on:
     - mediawiki

volumes:
  wiki-db-data: