version: '2'
services:
  commsy8_db:
    image: mariadb:10.1
    container_name: commsy8_db
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - "4003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commsy
      MYSQL_USER: commsy
      MYSQL_PASSWORD: commsy

  commsy8_nginx:
    build: ./build/nginx
    container_name: commsy8_nginx
    ports:
      - "8080:80"
    links:
      - commsy8_php
    volumes_from:
      - commsy8_php
    volumes:
      - "./logs/nginx:/var/log/nginx"

  commsy8_php:
    build: ./build/php-fpm
    container_name: commsy8_php
    expose:
      - "9000"
    volumes:
      - "./..:/var/www/html"
      - "./debug:/tmp"
    links:
      - commsy8_db
    environment:
      COMMSY_DB_NAME: commsy
      COMMSY_DB_USER: commsy
      COMMSY_DB_PASSWORD: commsy
      COMMSY_DB_HOST: db