version: "2"

services:
  commsy_db:
    image: mariadb:10.1
    container_name: commsy_db
    volumes:
      - "./.data/db:/var/lib/mysql"

  commsy_nginx:
    build: ./nginx
    container_name: commsy_nginx
    links:
      - commsy_php
    volumes_from:
      - commsy_php
    volumes:
      - "./.data/logs/nginx:/var/log/nginx"

  commsy_elastic:
    build: ./elasticsearch
    container_name: commsy_elastic
    volumes:
      - "./.data/elastic:/usr/share/elasticsearch/data"

  commsy_php:
    build: ./commsy_dev
    container_name: commsy_php
    volumes:
      - "./.data/logs/commsy:/var/www/commsy/var/logs"
      - "./.data/files:/var/www/commsy/files"
    links:
      - commsy_db
      - commsy_elastic