services:
    commsy_mediawiki.mediawiki:
        class: CommsyMediawikiBundle\Services\MediawikiService
        arguments:
            - '@commsy_legacy.environment'
            - '%commsy.mediawiki.apiUrl%'