services:
    commsy_mediawiki.mediawiki:
        class: App\Services\MediawikiService
        arguments:
            - '@commsy_legacy.environment'
            - '%commsy.mediawiki.apiUrl%'
            - '%commsy.mediawiki.consumerKey%'
            - '%commsy.mediawiki.consumerSecret%'
            - '%commsy.mediawiki.accessToken%'
            - '%commsy.mediawiki.accessSecret%'