# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

api_login:
    path: /api/v2/login_check
    methods: ['POST']

api_doc:
    path: /api/v2/doc
    controller: api_platform.action.documentation
