# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: '%env(LOCALE)%'

    commsy.elastic.prefix: '%env(ELASTIC_INDEX)%'

    commsy.force_theme: '%env(FORCE_THEME)%'

    files_directory: '%kernel.project_dir%/files'
    themes_directory: '%kernel.project_dir%/public/css/themes'

    commsy.metrics.cache_namespace: "%env(API_METRICS_CACHE_NAMESPACE)%"

    # Autosaving
    commsy.autosave.mode: 0         # possible modes: 0 -> unvisible, 1 -> verbose / silent, 2 -> verbose / counter
    commsy.autosave.limit: 6        # limit in minutes

    # Cookie management
    commsy.cookie.domain: ~
    commsy.cookie.path: ~

    # E-Mail
    commsy.email.from: '%env(EMAIL_FROM)%'

    # E-Mail Upload
    commsy.upload.enabled: '%env(bool:EMAIL_UPLOAD_ENABLED)%'
    commsy.upload.server: '%env(EMAIL_UPLOAD_SERVER)%'
    commsy.upload.port: '%env(EMAIL_UPLOAD_PORT)%'
    commsy.upload.options: '%env(EMAIL_UPLOAD_OPTIONS)%'
    commsy.upload.account: '%env(EMAIL_UPLOAD_ACCOUNT)%'
    commsy.upload.password: '%env(EMAIL_UPLOAD_PASSWORD)%'

    # Login
    commsy.login.shibboleth_direct_login: false
    commsy.login.shibboleth_redirect_url: ''
    commsy.login.shibboleth_deactivate_direct_login_by_portal_id: ''

    # Security / Data Privacy
    # Overwrite entries with "overwritten because of data security" when deleting a user
    # default = false
    # do nothing = true
    # set flag = flag
    commsy.security.privacy_disable_overwriting: '%env(uppercase:DATA_PRIVACY_OVERWRITING)%'
    commsy.security.allow_moderator_takeover: true      # allows all moderators to take over another user by default

    # Settings
    commsy.settings.export_temp_folder: 'var/temp/zip_export'       # Where to store the temporary export files
    commsy.settings.delete_days: 182        # Delete entries in database marked as deleted delete_days old
    commsy.settings.session_lifetime: 6     # Session lifetime in hours
    commsy.settings.proxy_ip: '%env(PROXY_IP)%'      # Proxy Ip
    commsy.settings.proxy_port: '%env(PROXY_PORT)%'      # Propxy Port
    commsy.settings.single_cat_selection: false     # Single selection for categories
    commsy.settings.item_locking: true     # Temporary protect items from beeing edited by different users simultaneously

    # Etherpad
    commsy.etherpad.enabled: '%env(bool:ETHERPAD_ENABLED)%'
    commsy.etherpad.api_key: '%env(ETHERPAD_API_KEY)%'
    commsy.etherpad.api_url: '%env(ETHERPAD_API_URL)%'
    commsy.etherpad.base_url: '%env(ETHERPAD_BASE_URL)%'

    # Dates
    commsy.dates.timezone: '%env(TIMEZONE)%'
    craue_twig_extensions.formatDateTime.datetype: medium
    craue_twig_extensions.formatDateTime.timetype: short

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true
        #public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DataFixtures/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Event/'
            - '../src/Form/Model/'
            - '../src/Kernel.php'
            - '../src/Mail/Messages/'
            - '../src/Message/'
            - '../src/Model/'
            - '../src/Proxy/'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\DataFixtures\AppFixtures:
        autowire: false
        autoconfigure: false
        tags:
            - 'doctrine.fixture.orm'

    _instanceof:
        App\Form\DataTransformer\DataTransformerInterface:
            tags: [ 'app.data_transformer' ]
        App\Cron\Tasks\CronTaskInterface:
            tags: [ 'app.cron_task' ]
        App\Database\DatabaseCheck:
            tags: [ 'app.database.check' ]
        App\Metrics\MetricInterface:
            tags: [ 'app.metric' ]

    # Event subscriber
    App\EventSubscriber\KernelSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # Environment Variable Processors
    App\DependencyInjection\UppercasingEnvVarProcessor:
        tags: ['container.env_var_processor']

    # Legacy Environment
    commsy_legacy.environment:
        alias: App\Services\LegacyEnvironment

    App\Services\LegacyEnvironment:
        arguments:
            $projectDir: '%kernel.project_dir%'

    commsy_legacy.category_service:
        alias: App\Utils\CategoryService

    commsy_legacy.room_service:
        alias: App\Utils\RoomService

    commsy_legacy.user_service:
        alias: App\Utils\UserService

    commsy_legacy.item_service:
        alias: App\Utils\ItemService

    # Filter types
    commsy.filter.rubric:
        class: App\Filter\RubricFilterType
        arguments: ['@commsy_legacy.room_service', '@request_stack']
        tags:
            - { name: form.type }

    commsy.filter.hashtag:
        class: App\Filter\HashTagFilterType
        arguments: ['@request_stack', '@commsy_legacy.room_service']
        tags:
            - { name: form.type }

    commsy.filter.category:
        class: App\Filter\CategoryFilterType
        arguments: ['@request_stack', '@commsy_legacy.category_service', '@commsy_legacy.room_service']
        tags:
            - { name: form.type }

    commsy.filter.participant:
        class: App\Filter\ParticipantFilterType
        arguments: ['@request_stack', '@commsy_legacy.user_service']
        tags:
            - { name: form.type }

    commsy.filter.calendar:
        class: App\Filter\CalendarFilterType
        arguments: ['@request_stack', '@commsy.calendars_service']
        tags:
            - { name: form.type }

    # Menu
    commsy.menu.builder:
        class: App\Menu\MenuBuilder
        arguments:
            $factory: '@knp_menu.factory'

    commsy.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ['@commsy.menu.builder', createMainMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    commsy.menu.settings:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createSettingsMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: settings }

    commsy.menu.portal_settings:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createPortalSettingsMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: portal_settings }

    commsy.menu.account:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createAccountMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: account }

    commsy.menu.profile:
        class: Knp\Menu\MenuItem
        factory: ['@commsy.menu.builder', createProfileMenu]
        arguments: ['@request_stack']
        tags:
            - { name: knp_menu.menu, alias: profile }

    # Voter
    commsy.security.category_voter:
        class: App\Security\Authorization\Voter\CategoryVoter
        arguments: ['@commsy_legacy.environment']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.hashtag_voter:
        class: App\Security\Authorization\Voter\HashtagVoter
        arguments: ['@commsy_legacy.environment']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.item_voter:
        class: App\Security\Authorization\Voter\ItemVoter
        arguments: ['@commsy_legacy.environment', '@commsy_legacy.item_service', '@commsy_legacy.room_service', '@commsy_legacy.user_service', '@request_stack']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.user_voter:
        class: App\Security\Authorization\Voter\UserVoter
        arguments: ['@commsy_legacy.environment', '@commsy_legacy.user_service', '@commsy_legacy.room_service']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.calendars_voter:
        class: App\Security\Authorization\Voter\CalendarsVoter
        arguments: ['@commsy_legacy.environment']
        public: false
        tags:
            - { name: security.voter }

    commsy.security.rubric_voter:
        class: App\Security\Authorization\Voter\RubricVoter
        arguments: ['@commsy_legacy.environment']
        public: false
        tags:
            - { name: security.voter }

    App\Security\Authorization\Voter\FileVoter:
        autowire: true
        autoconfigure: true

    commsy.etherpad_form_listener:
        class: App\Form\Type\Event\AddEtherpadFormListener
        arguments: ["@service_container"]
        tags:
            - { name: form.event_subscriber }

    # EventSubscribers
    commsy.subscriber.edit:
        class: App\EventSubscriber\CommsyEditSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }

    # Search
    commsy.search.manager:
        alias: App\Search\SearchManager

    App\Form\DataTransformer\TransformerManager:
        arguments:
            - !tagged_iterator app.data_transformer

    App\Cron\CronManager:
        class: App\Cron\CronManager
        arguments:
            $projectDir: '%kernel.project_dir%'
            $cronTasks: !tagged_iterator app.cron_task

    App\Metrics\PrometheusCollector:
        arguments:
            - !tagged_iterator app.metric

    App\Search\SearchManager:
        autowire: false
        arguments:
            $commsyFinder: '@FOS\ElasticaBundle\Finder\TransformedFinder'
            $userService: '@App\Utils\UserService'
            $itemService: '@App\Utils\ItemService'

    App\Search\MultiIndex:
        arguments:
            $client: '@fos_elastica.client.default'
            $name: 'commsy'
        calls:
            - [addIndices, [[
                 '@fos_elastica.index.commsy_announcement',
                 '@fos_elastica.index.commsy_date',
                 '@fos_elastica.index.commsy_discussion',
                 '@fos_elastica.index.commsy_label',
                 '@fos_elastica.index.commsy_user',
                 '@fos_elastica.index.commsy_room',
                 '@fos_elastica.index.commsy_todo',
                 '@fos_elastica.index.commsy_material',
            ]]]

    Elastica\SearchableInterface: '@App\Search\MultiIndex'

    App\Search\Transformer\ElasticaToModelTransformerCollection:
        arguments:
            - {
                announcement: '@fos_elastica.elastica_to_model_transformer.commsy_announcement',
                date: '@fos_elastica.elastica_to_model_transformer.commsy_date',
                discussion: '@fos_elastica.elastica_to_model_transformer.commsy_discussion',
                label: '@fos_elastica.elastica_to_model_transformer.commsy_label',
                room: '@fos_elastica.elastica_to_model_transformer.commsy_room',
                todo: '@fos_elastica.elastica_to_model_transformer.commsy_todo',
                user: '@fos_elastica.elastica_to_model_transformer.commsy_user',
                material: '@fos_elastica.elastica_to_model_transformer.commsy_material',
            }
    FOS\ElasticaBundle\Transformer\ElasticaToModelTransformerInterface: '@App\Search\Transformer\ElasticaToModelTransformerCollection'

    FOS\ElasticaBundle\Finder\TransformedFinder: ~
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@FOS\ElasticaBundle\Finder\TransformedFinder'

    app.elastica.object_persister.commsy_announcement:
        alias: 'fos_elastica.object_persister.commsy_announcement'
        public: true

    app.elastica.object_persister.commsy_date:
        alias: 'fos_elastica.object_persister.commsy_date'
        public: true

    app.elastica.object_persister.commsy_discussion:
        alias: 'fos_elastica.object_persister.commsy_discussion'
        public: true

    app.elastica.object_persister.commsy_label:
        alias: 'fos_elastica.object_persister.commsy_label'
        public: true

    app.elastica.object_persister.commsy_room:
        alias: 'fos_elastica.object_persister.commsy_room'
        public: true

    app.elastica.object_persister.commsy_todo:
        alias: 'fos_elastica.object_persister.commsy_todo'
        public: true

    app.elastica.object_persister.commsy_user:
        alias: 'fos_elastica.object_persister.commsy_user'
        public: true

    app.elastica.object_persister.commsy_material:
        alias: 'fos_elastica.object_persister.commsy_material'
        public: true

    FOS\ElasticaBundle\Persister\AsyncPagerPersister:
        arguments:
            - '@fos_elastica.pager_persister_registry'
            - '@fos_elastica.pager_provider_registry'
            # In the bundle this messagebus is different, but we should pass official Symfony bus.
            - '@Symfony\Component\Messenger\MessageBusInterface'
        tags:
            - { name: "fos_elastica.pager_persister", persisterName: "async" }

    FOS\ElasticaBundle\Message\Handler\AsyncPersistPageHandler:
        tags: [ messenger.message_handler ]

    commsy.search.indexable_checker:
        alias: App\Search\IndexableChecker

    # Form types
    App\Form\Type\ExtensionSettingsType:
        tags:
            - { name: form.type }

    commsy.form.type.material:
        class: App\Form\Type\MaterialType
        arguments: ['@commsy.etherpad_form_listener']
        tags:
            - { name: form.type }

    # Mail
    App\Mail\MessageBuilder:
        arguments:
            $emailFrom: '%commsy.email.from%'

    # Utils
    App\Utils\MailAssistant:
        arguments:
            $twig: '@twig'

    # Commands
    App\Command\EmailUploadCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $uploadEnabled: '%commsy.upload.enabled%'
            $uploadServer: '%commsy.upload.server%'
            $uploadPort: '%commsy.upload.port%'
            $uploadOptions: '%commsy.upload.options%'
            $uploadAccount: '%commsy.upload.account%'
            $uploadPassword: '%commsy.upload.password%'

    # Database checks
    App\Database\DatabaseChecks:
        arguments:
            $checks: !tagged_iterator app.database.check

    # Feed
    debril.rss_atom.provider:
        class: App\Feed\CommsyFeedContentProvider

    # Monolog
    commsy.monolog.handler.doctrine_orm:
        class: App\Monolog\Handler\DoctrineORMHandler
        arguments: ['@doctrine.orm.entity_manager']

    # Services
    commsy.avatar_service:
        alias: App\Services\AvatarService

    App\Services\AvatarService:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'

    App\Services\PrintService:
        arguments:
            $pdf: '@knp_snappy.pdf'
            $proxyIp: '%commsy.settings.proxy_ip%'
            $proxyPort: '%commsy.settings.proxy_port%'

    commsy.copy_service:
        alias: App\Services\MarkedService

    commsy.calendars_service:
        class: App\Services\CalendarsService

    commsy.roomcategories_service:
        class: App\Services\RoomCategoriesService
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

    commsy.room_feed_generator:
        class: App\RoomFeed\RoomFeedGenerator
        public: true
        arguments:
            - '@commsy_legacy.environment'
            - '@commsy_legacy.room_service'
            - '@commsy_legacy.item_service'

    # actions
    commsy.action.mark_read.generic:
        class: App\Action\MarkRead\MarkReadAction
        autowire: true
        arguments:
            $markReadStrategy: '@App\Action\MarkRead\MarkReadGeneric'


    App\Action\MarkRead\MarkReadAction: '@commsy.action.mark_read.generic'

    # Response
    App\Http\JsonDataResponse:
        autowire: false

    App\Http\JsonErrorResponse:
        autowire: false

    App\Http\JsonHTMLResponse:
        autowire: false

    App\Http\JsonRedirectResponse:
        autowire: false

    # SessionHandler
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'

    # FormatDateTimeExtension
    Craue\TwigExtensionsBundle\Twig\Extension\FormatDateTimeExtension:
        alias: twig.extension.craue_formatDateTime
    
    # Doctrine
    Doctrine\Migrations\Version\DbalMigrationFactory: ~
    App\Migrations\Factory\MigrationFactoryDecorator:
        decorates: Doctrine\Migrations\Version\DbalMigrationFactory
        arguments: [ '@App\Migrations\Factory\MigrationFactoryDecorator.inner', '@service_container' ]
