FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.21

#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin remove x-pack

#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch mapper-attachments
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-attachment