// to be used with HTML code generated by `cs_form_view_left_agora.php.php->_getPasswordAsHTML()` & CSS in `../css/custom.css`
// see <https://bootsnipp.com/snippets/xpM4m> & <https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/wheeler>
$(document).ready(function()
{
    /** Colors the background of a password input field according to the strength of the entered password. */
    $('#password').on('propertychange change keyup paste input', function()
    {
        // TODO: only use the first 128 characters to stop this from blocking the browser if a giant password is entered
        var password = $(this).val();
        var passwordScore = zxcvbn(password)['score'];

        var updateMeter = function(width, background, textcolor, text) {
            $('.password-background').css({"width": width, "background-color": background});
            $('.strength').text(text).css('color', textcolor);
        }

        var updateShowPasswordLink = function(display) {
            $('.show-password').css('display', display);
        }

        // TODO: proper localization
        var strength = { "none":"", "very_weak":"very weak", "weak":"weak", "medium":"medium", "strong":"strong", "very_strong":"very strong" };
        if ($('html').attr('lang') === 'de') {
            strength = { "none":"", "very_weak":"sehr schwach", "weak":"schwach", "medium":"mittel", "strong":"stark", "very_strong":"sehr stark" };
        }

        if (password.length === 0) {
            updateShowPasswordLink('none');
        } else {
            updateShowPasswordLink('inline');
        }

        if (passwordScore === 0) {
            if (password.length === 0) {
                updateMeter("0%", "#ffa0a0", "#cc3333", strength['none']);
            } else {
                updateMeter("20%", "#ffa0a0", "#cc3333", strength['very_weak']);
            }
        }
        if (passwordScore == 1) updateMeter("40%", "#ffb78c", "#ff6600", strength['weak']);
        if (passwordScore == 2) updateMeter("60%", "#ffec8b", "#ffcc00", strength['medium']);
        if (passwordScore == 3) updateMeter("80%", "#c3ff88", "#33cc00", strength['strong']);
        if (passwordScore == 4) updateMeter("100%", "#ACE872", "#339900", strength['very_strong']);
    });

    /** Toggles the display kind (clear text vs bullets) of the password entered in a password input field. */
    $('.show-password').click(function(event)
    {
        // TODO: proper localization
        var text = { "show_password":"Show password", "hide_password":"Hide password" };
        if ($('html').attr('lang') === 'de') {
            text = { "show_password":"Passwort anzeigen", "hide_password":"Passwort verbergen" };
        }

        event.preventDefault();
        if ($('#password').attr('type') === 'password') {
            $('#password').attr('type', 'text');
            $('.show-password').text(text['hide_password']);
        } else {
            $('#password').attr('type', 'password');
            $('.show-password').text(text['show_password']);
        }
    });
});
