<?php

/*
 * This file is part of CommSy.
 *
 * (c) Matthias Finck, Dirk Fust, Oliver Hankel, Iver Jackewitz, Michael Janneck,
 * Martti Jeenicke, Detlev Krause, Irina L. Marinescu, Timo Nolte, Bernd Pape,
 * Edouard Simon, Monique Strauss, Jose Mauel Gonzalez Vazquez, Johannes Schultze
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Tests\Factory;

use App\Entity\Announcement;
use App\Entity\Room;
use App\Entity\User;
use App\Services\LegacyEnvironment;
use LogicException;
use ReflectionProperty;
use Tests\Factory\Concerns\PrimesLegacyEnvironment;
use Zenstruck\Foundry\Object\Instantiator;
use Zenstruck\Foundry\Persistence\PersistentObjectFactory;

/**
 * @extends PersistentObjectFactory<Announcement>
 *
 * Creates an announcement through the **legacy** manager chain
 * (`cs_announcement_manager::getNewItem()` + `save()`) — i.e. exactly the path
 * a controller takes. This keeps the fixture faithful to production and avoids
 * duplicating insert logic in the factory.
 *
 * The legacy save happens inside the DAMA-managed DBAL transaction because
 * `db_mysql_connector` resolves the same `database_connection` service, so
 * nothing escapes the per-test rollback.
 *
 * Required factory inputs:
 *  - `room`    App\Entity\Room — the containing context
 *  - `creator` App\Entity\User — priming the legacy current-user slot
 */
final class AnnouncementFactory extends PersistentObjectFactory
{
    use PrimesLegacyEnvironment;

    public function __construct(
        private readonly LegacyEnvironment $legacyEnvironment,
    ) {
        parent::__construct();
    }

    public static function class(): string
    {
        return Announcement::class;
    }

    protected function defaults(): array|callable
    {
        return [
            'title' => self::faker()->sentence(4),
            'description' => self::faker()->paragraph(),
            'room' => null,
            'creator' => null,
        ];
    }

    protected function initialize(): static
    {
        // The legacy save() does its own INSERTs into `items` + `announcement`.
        // We bypass Foundry's Doctrine persistence and run the legacy chain in
        // an afterInstantiate() hook, then copy the generated id back onto the
        // draft so the caller has a usable entity reference.
        return $this
            ->withoutPersisting()
            ->instantiateWith(Instantiator::withConstructor()->allowExtra('room', 'creator'))
            ->afterInstantiate(function(Announcement $announcement, array $attributes): void {
                $room = $attributes['room'] ?? null;
                $creator = $attributes['creator'] ?? null;

                if (!$room instanceof Room) {
                    throw new LogicException('AnnouncementFactory requires "room" (App\Entity\Room).');
                }
                if (!$creator instanceof User) {
                    throw new LogicException('AnnouncementFactory requires "creator" (App\Entity\User).');
                }

                $env = $this->primeLegacyEnvironment($room, $creator);

                $item = $env->getAnnouncementManager()->getNewItem();
                $item->setTitle($announcement->getTitle());
                if ($announcement->getDescription() !== null) {
                    $item->setDescription($announcement->getDescription());
                }
                $item->setContextID($room->getItemId());
                // `enddate` is NOT NULL in the schema — legacy defaults to the
                // announcement's creation date when the user did not pick one.
                $item->setSecondDateTime(date('Y-m-d H:i:s'));
                // Turn the swallowed legacy trigger_error('Problems creating announcement.')
                // into a real test failure instead of silently producing orphan `items` rows.
                set_error_handler(function(int $errno, string $errstr): bool {
                    throw new LogicException(sprintf('Legacy save() warning: %s', $errstr));
                }, E_USER_WARNING);
                try {
                    $item->save();
                } finally {
                    restore_error_handler();
                }

                $itemId = $item->getItemID();
                if ($itemId <= 0) {
                    throw new LogicException('Legacy save() did not return a valid item id.');
                }

                // `itemId` is private and generated by Doctrine (#[GeneratedValue]),
                // so there is no setter — reflection is the pragmatic hook.
                $idProperty = new ReflectionProperty(Announcement::class, 'itemId');
                $idProperty->setValue($announcement, $itemId);
                $announcement->setContextId($room->getItemId());
            });
    }

    protected function getLegacyEnvironmentService(): LegacyEnvironment
    {
        return $this->legacyEnvironment;
    }
}
