services:
    commsy.etherpad_service:
        class: App\Services\EtherpadService
        arguments: ["@service_container"]

    etherpad.etherpad_edit_subscriber:
        class: App\EventSubscriber\EtherpadEditSubscriber
        arguments: ["@service_container", "@commsy_legacy.material_service"]
        tags:
            - { name: kernel.event_subscriber }