# main/config/routing.yml
default:
    path: /
    defaults:
        _controller: Application\Controller\DefaultController::defaultAction

test:
    path: /test
    defaults:
        _controller: Application\Controller\TestController::indexAction