define({
	additionalAdd:				"Einen weiteren Teilnehmer hinzufügen",
	additionalDescription:		"Zusätzlich zur Auswahl einer Gruppe können Sie hier unabhängig davon Teilnehmer für die Umfrage ergänzen.",
	additionalFirstName:		"Vorname",
	additionalLabel:			"Zusätzliche Teilnehmer",
	additionalLastName:			"Nachname",
	additionalMail:				"Mailadresse",
	buttonClose:				"Schließen",
	buttonSubmit:				"Teilnehmer einladen",
	close:						"schließen",
	errorMail:					"Falsches Mail-Format",
	errorMissing:				"Bitte geben Sie einen Wert an",
	inviteIntro:				"Sie können die Mitglieder dieses Raumes zu der ausgewählten Umfrage einladen.",
	group:						"Gruppe",
	groupLoading:				"Lade Gruppen...",
	groupNone:					"Keine Gruppe",
	mailAddresses:				"Empfänger",
	mailAddressesDesc:			"In dieser Textbox können Sie beliebig viele Mailadressen angeben. Als Trennzeichen können Sie ein Leerzeichen, eine neue Zeile, ein Semikolon oder ein Komma verwenden.",
	mailSubject:				"Betreff",
	mailText:					"Inhalt",
	mailTextDesc:				"Innerhalb dieses Textes können Sie die Plathalter {SURVEY_TITLE} und {SURVEY_URL} für den Titel und die Adresse der Umfrage verwenden.",
	mailTemplate:				"Einleitung...\n\nUmfrage Titel: {SURVEY_TITLE}\nUmfrage URL: {SURVEY_URL}\n\nGrußformel...",
	title:						"Teilnehmer",
	tokenDescription:			"Wenn Sie diese Funktion aktiveren wird die Umfrage nur für eingeladene Raummitglieder zugänglich sein.",
	useTokens:					"Zugangsschlüssel verwenden"
});