name: CI

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    test:
        name: Run Tests
        env:
            APP_ENV: test
            DATABASE_URL: mysql://root:root@127.0.0.1:3306/commsy_test
            ELASTICSEARCH_URL: http://127.0.0.1:9200/
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['8.0', '8.1']
        services:
            db:
                image: mariadb:10.6
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: commsy_test
                ports:
                    - 3306:3306
            elastic:
                image: bitnami/elasticsearch:7
                ports:
                    - 9200:9200
                env:
                    discovery.type: single-node
                    ELASTICSEARCH_PLUGINS: ingest-attachment
                options: >-
                    --health-cmd "curl http://localhost:9200/_cluster/health"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 10

        steps:
            -   name: actions/checkout
                uses: actions/checkout@v3

            -   name: Setup node
                uses: actions/setup-node@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: zip, imap, ldap, apcu
                    ini-values: apc.enable_cli=1, date.timezone=Europe/Berlin
                    tools: composer:v2

            -   name: Install yarn deps
                run: yarn install

            -   name: Install php deps
                run: composer install --no-progress

            -   name: Generate JWT keypair
                run: bin/console lexik:jwt:generate-keypair

            -   name: Build frontend package
                run: yarn build

            -   name: Run tests
                run: vendor/bin/codecept run --env github