name: Release docker

on:
    workflow_dispatch:
    push:
        branches:
            - '10.1'
        tags:
            - 'v*'

jobs:
    release-docker:
        name: Create and push docker images
        needs: test
        runs-on: ubuntu-latest
        steps:
            -   name: actions/checkout
                uses: actions/checkout@v3

            -   name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            # PHP image
            -   name: docker/metadata-action
                uses: docker/metadata-action@v4
                id: meta_php
                with:
                    images: |
                        effectivewebwork/commsy
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{major}}.{{minor}}
                    flavor: |
                        suffix=-php-fpm,onlatest=true

            -   name: Build php image and push
                uses: docker/build-push-action@v3
                with:
                    context: .
                    push: true
                    target: commsy_php
                    tags: ${{ steps.meta_php.outputs.tags }}
                    labels: ${{ steps.meta_php.outputs.labels }}

            # caddy image
            -   name: docker/metadata-action
                uses: docker/metadata-action@v4
                id: meta_caddy
                with:
                    images: |
                        effectivewebwork/commsy
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{major}}.{{minor}}
                    flavor: |
                        suffix=-caddy,onlatest=true

            -   name: Build caddy image and push
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: true
                    target: commsy_caddy
                    tags: ${{ steps.meta_caddy.outputs.tags }}
                    labels: ${{ steps.meta_caddy.outputs.labels }}

            # elasticsearch image
            -   name: docker/metadata-action
                uses: docker/metadata-action@v4
                id: meta_elastic
                with:
                    images: |
                        effectivewebwork/commsy
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{major}}.{{minor}}
                    flavor: |
                        suffix=-elastic,onlatest=true

            -   name: Build elasticsearch image and push
                uses: docker/build-push-action@v3
                with:
                    context: ./docker/elasticsearch
                    push: true
                    tags: ${{ steps.meta_elastic.outputs.tags }}
                    labels: ${{ steps.meta_elastic.outputs.labels }}
