name: Release sources

# Only run when pushing tags
on:
    push:
        tags:
            - 'v*'

jobs:
    release-gh:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        env:
            APP_ENV: prod
        steps:
            -   name: actions/checkout
                uses: actions/checkout@v2

            -   name: Setup node
                uses: actions/setup-node@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    extensions: zip, imap, ldap, apcu
                    ini-values: apc.enable_cli=1, date.timezone=Europe/Berlin
                    tools: composer:v2

            -   name: Install php deps
                run: composer install --prefer-dist --no-dev --no-scripts --no-progress --no-suggest

            -   name: Generate JWT keypair
                run: bin/console lexik:jwt:generate-keypair

            -   name: Dump env
                run: composer dump-env prod

            -   name: Dump autoload
                run: composer dump-autoload --classmap-authoritative --no-dev

            -   name: Run post install scripts
                run: composer run-script --no-dev post-install-cmd

            -   name: Install yarn deps
                run: yarn install
                
            -   name: Build frontend package
                run: yarn build

            -   name: Get tag
                id: tag
                uses: dawidd6/action-get-tag@v1

            -   name: Archive Release
                uses: thedoctor0/zip-release@master
                with:
                    filename: commsy-${{ steps.tag.outputs.tag }}.zip
                    exclusions: '*.git* /assets/* /docker/* /*node_modules/* /tests/* .dockerignore .editorconfig .env.test .php-cs-fixer.dist.php .travis.yml codeception.yml composer.lock composer.phar docker-compose* Dockerfile Makefile package.json php* rector.php symfony.lock tsconfig.json webpack.config.js yarn.lock'

            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: commsy-${{ steps.tag.outputs.tag }}.zip
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
